export const NEXT_DEVICE = "NEXT_DEVICE";
export const PREV_DEVICE = "PREV_DEVICE";
export const ADD_BACKGROUND = "ADD_BACKGROUND";
export const DELETE_BACKGROUND = "DELETE_BACKGROUND";
export const CHANGE_BACKGROUND = "CHANGE_BACKGROUND";
export const ADD_SIZE = "ADD_SIZE";
